# Generated by Django 4.2.13 on 2024-05-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_graphdata_graph_image_alter_graphdata_x_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdata',
            name='graph_image',
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='x_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='y_values',
            field=models.TextField(),
        ),
    ]
