# Generated by Django 4.2.13 on 2024-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_remove_graphdata_graph_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='grid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='title',
            field=models.CharField(default='Graph', max_length=100),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='x_label',
            field=models.CharField(default='X', max_length=100),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='y_label',
            field=models.CharField(default='Y', max_length=100),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='graph_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='x_values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='y_values',
            field=models.CharField(max_length=1000),
        ),
    ]
